### ISSUE TITLE
Question about Windows 10, Visual Studio 2019

### ISSUE THREAD

**Issue by nerdburt** [9track/dlsw#1]
Hello, I am attempting to compile this on Windows 10/20H2 for a mainframe experiment with SNA testing, and have been using Visual Studio Community 2019.

For some reason, it says I do not have a correct version of Visual Studio, but in looking at the code, it doesn't make sense.

I have tried to echo the code in the output:
1>vstools.cmd : error : No supported version of Visual Studio is installed
**1>vserver = 80
1>vsname = vs2005
1>VCVARSDIR =**
1>rc
1>makefile.bat ended on Tue 02/16/2021 at 15:24:57.37, rc=1

As an alternative, I am trying to compile with Visual Studio 2008 Express, and am getting other errors about trying to compile to target platform "WINNT_VISTA" and it halts.  Wondering if there is anything I can do for a quick fix in either the compiler(s) or in the vstools.cmd file?

I am a noob to Visual Studio, so hopefully it is not something obvious I have missed....:)

**Comment by 9track** [comment]
I'm guessing that vstools.cmd is from the Hercules repository. You should not need any of that to build dlswserver. I've updated the readme to show the commands needed to compile this. The simplest way to build dlswserver on Windows is with a Visual Studio command prompt:
```
cl /out:dlswserver.exe dlswserver.c /link ws2_32.lib
```
It should be noted that dlswserver is a standalone program that pretends to be a DLSw capable router, listening on port 2065. It provides an example of how to establish a link with a DLSw peer (such as a Cisco router) so that SNA packets can be exchanged.

**Comment by nerdburt** [comment]
Hello, thank you for the quick response.  I just realized I had meant to publish this question in Hyperion and not here, but I also am trying to compile the dlswserver, so this will help get me started quickly.    I had some issues getting this working in Visual Studio 2019, but was able to get it working!  Had to ensure the Ws2_32.lib was added to the linker, and under project properties, add mainCRTStartup as Entry Point.   Compiled it, McAfee deleted it (got that out of quarantine) and can now test drive it.  Thanks for the assistance! :)
